name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install
          uses: ianwalter/puppeteer@master
          with:
            args: npm install
        - name: Test
          run: |
            npm install base-64
            npm install utf8
            
