name: CI
on:
  workflow_dispatch:
    inputs:
      STORY_ID:
        description: 'Test'
        required: true
        default: 'QA-343'
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN  }}
  SHA: ${{github.sha}}
  STORY_ID: ${{ github.event.inputs.STORY_ID }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test
      if: ${{ always() }}
      run: |
        sh ./test.sh ${{ env.STORY_ID }} ${{ env.GITHUB_TOKEN }} ${{ env.SHA }}
            
